[default]
src = 'contracts'
test = 'tests'

# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.11'
auto_detect_solc = false
# Increase optimizer_runs
optimizer = true
optimizer_runs = 200

# See more config options https://github.com/gakonst/foundry/tree/master/config
